### ISSUE TITLE
TODOs on otel go launcher

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/opentelemetry-go-contrib#410]
some items to cover before finalizing [launcher PR](https://github.com/honeycombio/opentelemetry-go-contrib/pull/400):

- [ ] #423
  - https://github.com/honeycombio/opentelemetry-go-contrib/pull/400/commits/2b6fbcea1691b10a29fc9d83e542673b953f4f15
- [ ] #417
- [ ] #418
- [ ] #419
- [ ] #420
- [ ] #421
- [ ] #422

**Comment by kentquirk** [comment]
Notes:
header parsing might need to be more robust -- string trim, no equals, quoted values?

**Comment by MikeGoldsmith** [comment]
I think a simple implementation of header parsing is fine to start with. Trimming whitespace, must contains `=`, etc. I don't think we need to worry too much about quoted values. The OTel SDK only doesn't do that for now too.

Having a default error hander / logger is useful. Otherwise if you fail to parse env vars, or use a vendor package that has validation, you may not see the errors.

**Comment by JamieDanielson** [comment]
these are now tracked in individual issues, with the milestone https://github.com/honeycombio/opentelemetry-go-contrib/milestone/1
